### ISSUE TITLE
Document how to use Rails caching with paquito?

### ISSUE THREAD

**Issue by joevandyk** [Shopify/paquito#35]
We've ran into similar issues with Mashall that the blog post at https://shopify.engineering/caching-without-marshal-part-two-messagepack goes into. We're interested in using Paquito to possibly solve some of those issues. 

It would be nice if there was a section in the Paquito Readme that went over the basics of how to use Paquito to do basic caching of ActiveRecord objects in Rails.  

I also noticed that the README didn't mention ActiveRecordCoder at all.

Side question: https://github.com/Shopify/paquito/blob/7b97f481a3690fe5531aebe2273b779481cfa4ac/lib/paquito/active_record_coder.rb#L3 requires ActiveRecord >= 7 - it won't work with version 6?

**Comment by casperisfine** [comment]
> I also noticed that the README didn't mention ActiveRecordCoder at all.

It's an internal class, it shouldn't be used directly.

There's nothing special to serialize Active Record object, you just pass `ActiveRecord::Base` as an allowed type to `CodecFactory.build`: https://github.com/Shopify/paquito#codecfactory
